name: admin-dl
dependencies:
- openssl=1.0.2g=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.6.7=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - ansible==2.0.1.0
  - ecdsa==0.13
  - jinja2==2.8
  - markupsafe==0.23
  - paramiko==1.16.0
  - pycrypto==2.6.1
  - pyyaml==3.11

